name: Build Docker Images on PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile_frontend
          push: false
          platforms: linux/amd64,linux/arm64

      - name: Build backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile_backend
          push: false
          platforms: linux/amd64,linux/arm64
